### ISSUE TITLE
Segfault at shut down do to lack of loop exit

### ISSUE THREAD

**Issue by sonyccd** [epfl-lasa/record_ros#1]
recomend change to this.

`void Record::wait_for_callback(){  
    ros::Rate r(100); // 60 hz  
    while (!b_record&&ros::ok())  
    {  
        ros::spinOnce();  
        r.sleep();  
    }  
    ros::shutdown();  
}`

**Comment by gpldecha** [comment]
Ok, would you like to make a commit ?
